### ISSUE TITLE
exception accessing member variable in ternary

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#1]
The parser is failing on this code in dijit.Declaration:

declare(..., { ...
    mixins: [],
    ...
    buildRendering: function(){  
            this.mixins = this.mixins.length ? ...
});

It doesn't like this.mixins.length since it thinks that this.mixins is null.   Not sure how to deal w/that, other than rewriting it like:

```
        if(this.mixins.length){
            this.mixins = array.map(this.mixins, function(name){ return lang.getObject(name); } );
        }else{
            this.mixins = [ _Widget, _TemplatedMixin, _WidgetsInTemplateMixin ];
        }
```

The stack trace is:

ERR: dijit/t.js:72:31 TypeError: Cannot convert null to object
    at Value.getProperty (/Volumes/Data/workspace/docparse/lib/Value.js:181:33)
    at Scope.getVariable (/Volumes/Data/workspace/docparse/lib/Scope.js:177:25)
    at Object.MemberExpression (/Volumes/Data/workspace/docparse/lib/esprimaParser.js:607:59)
    at read (/Volumes/Data/workspace/docparse/lib/esprimaParser.js:239:27)
    at Object.readBinaryExpression (/Volumes/Data/workspace/docparse/lib/esprimaParser.js:189:15)
    at read (/Volumes/Data/workspace/docparse/lib/esprimaParser.js:239:27)
    at Object.ConditionalExpression (/Volumes/Data/workspace/docparse/lib/esprimaParser.js:395:15)
    at read (/Volumes/Data/workspace/docparse/lib/esprimaParser.js:239:27)
    at Object.AssignmentExpression (/Volumes/Data/workspace/docparse/lib/esprimaParser.js:247:16)
    at read (/Volumes/Data/workspace/docparse/lib/esprimaParser.js:239:27)

**Comment by wkeese** [comment]
Actually, I decided to just check in that workaround.    There are much bigger fish to fry than fixing this bug right away.
